/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.icesi.ciberSecurityProject.client.gui;

import co.edu.icesi.ciberSecurityProject.model.Commands;
import co.edu.icesi.ciberSecurityProject.model.User;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;

/**
 *
 * @author azo_6
 */
public class ClientsConnected extends javax.swing.JFrame {

    private DefaultListModel listModel;

    private User userLoggedIn;     
    /**
     * Creates new form ClientsConnected
     */
    public ClientsConnected(User newUser) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        userLoggedIn = newUser;
        
        jList1.addMouseListener(new MouseAdapter() {
    public void mouseClicked(MouseEvent evt) {
      
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {

            Rectangle r = jList1.getCellBounds(0, jList1.getLastVisibleIndex()); 

                if (r != null && r.contains(evt.getPoint())) { 
                    int index = jList1.locationToIndex(evt.getPoint()); 
                    ClientChat nuevoChat = new ClientChat();
                } 
        } else if (evt.getClickCount() == 3) {

            Rectangle r = jList1.getCellBounds(0, jList1.getLastVisibleIndex()); 

                if (r != null && r.contains(evt.getPoint())) { 
                    int index = jList1.locationToIndex(evt.getPoint()); 
                 }     
        }
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuarios conectados en este momento:");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Nada por aquí..." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public ArrayList onlineUserList(){
        ArrayList list = new ArrayList();
        ListModel model = jList1.getModel();

        for(int i=0; i < model.getSize(); i++){
        Object o =  model.getElementAt(i);
        list.add((String)o);
        }
        return list;
    }
    
    public void updateUserList(User user){
           if(user.getState().equals(Commands.CONNECTED)){
               listModel.addElement("user.nickname");
           }
           else if (user.getState().equals("offline")){
            DefaultListModel model = (DefaultListModel)jList1.getModel();
            int index = model.indexOf(user.getNickname());
            listModel.remove(index);
           }
       }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
